%YAML:1.0

# the dataset directory, change it to yours!
dataset_type: CFT
dataset_dir: /home/vbn/CFT2401/eo_image_files (4)
# map_file: CFT2401Map4.dat
viewer: true


# IC-GVINS多源融合定位算法配置文件
 
# 结果输出路径
# Output directory
outputpath: "../output/cft"
is_make_outputdir: true

# 时间信息, s
# Time length for GNSS/INS intialization
initlength: 1

# IMU原始数据频率, Hz
# IMU sample rate
imudatarate: 200

# 考虑地球自转补偿项
# Consider the Earth rotation
iswithearth: true

# 天线杆臂, IMU前右下方向, m
# GNSS lever-arm in IMU body frame (front-right-down)
antlever: [-0.37, 0.008, 0.353] 

# IMU噪声建模参数
# IMU noise parameters
imumodel:
    arw: 0.1        # deg/sqrt(hr)
    vrw: 0.1        # m/s/sqrt(hr)
    gbstd: 50.0     # deg/hr
    abstd: 50.0     # mGal
    corrtime: 1.0   # hr

# GNSS中断配置
# GNSS outage configurations, the GNSS will not be used after the gnssoutagetime 
isusegnssoutage: false
gnssoutagetime: 0

# 固定阈值GNSS抗差
# A fixed threshold (STD, m) for GNSS outlier culling
gnssthreshold: 20

# 是否开启可视化
# Use visualization
is_use_visualization: false

# 跟踪
# Tracking configurations
track_check_histogram: false    # 直方图检查, 避免出现光照变化较大的图像 (Check histogram for drastic illumulation change)
track_min_parallax: 100          # 关键帧最小像素视差 (The minmum parallax in pixels to choose a keyframe)
track_max_interval: 0.5         # 最大的关键帧间隔, 超过则插入观测帧, s (The maximum lenght to choose a observation frame)
track_max_features: 500         # 最大提取特征数量 (The maximum features to detect, may be more or less, see tracking.cc)

# 优化
# Optimization configurations
reprojection_error_std: 30        # 像素重投影误差 (The reprojection error std for optimizition and outlier culling)
optimize_windows_size: 10           # 滑动窗口大小 (The size of the sliding window, number of the keyframes )
optimize_num_iterations: 20         # 优化迭代次数 (The iterations in total)
optimize_estimate_extrinsic: false   # 是否估计相机和IMU的外参 (Estimate the extrinsic)
optimize_estimate_td: false          # 否估计相机和IMU之间的时间间隔 (Estimate the time delay)



cam0:
    # 内参 [fx, fy, cx, cy(, skew)]
    # Intrinsic parameters, pinhole model
    # intrinsic: [589.3666835307065, 589.3666835307065, 320, 240]
    # intrinsic: [207.81042982320338, 207.81042982320338, 320, 240]
    # intrinsic: [442.0250126480299, 442.0250126480299, 320, 240]
    intrinsic: [5974.8174296751813017811, 5974.8174296751813017811, 2041.90050415982250342495, 1497.28919883224034492741]

    # 畸变参数 [k1, k2, p1, p2(, k3)]
    # Distortion parameters
    distortion: [-0.07604263357930293732, 0.23293482575287602354, 0, 0]

    # 图像分辨率
    # Resolution
    resolution: [4096, 3000]

    # 相机IMU外参 (Camera-IMU extrinsic)
    # Pb = q_b_c * Pc + t_b_c
    # q (x, y, z, w)
    q_b_c: [0, 0, 0, 1]
    t_b_c: [0, 0, 0]

    # IMU和相机时间延时 (The time delay between the IMU and camera)
    # t_i = t_c + td
    td_b_c: 0.0
